### ISSUE TITLE
Error when using setting command

### ISSUE THREAD

**Issue by StrangerGithuber** [AlexArtaud-Dev/Roomba-V2#3]
Hello
When I am using the settings command then I get this error:
```
Desktop\Roomba-V2-main\node_modules\.pnpm\mongoose@6.0.15\node_modules\mongoose\lib\document.js:2913
    this.$__.validationError = new ValidationError(this);
                               ^

ValidationError: Guild validation failed: log: Cast to Object failed for value "917126520533835796" (type string) at path "log"

at async SettingCommand.exec (C:\\Desktop\Roomba-V2-main\src\commands\administration\setting.js:33:13)
```

I tried to setup the log channel and welcome channel but I get the same error.
I tried to use the commands like this:
```
!setting log 917126520533835796
!setting logChannel 917126520533835796
!setting log true
!setting log true 917126520533835796
!setting logChannel true
```

Do I am using wrong way the command or something else the problem?
Thank you in advance the answer.

**Comment by AlexArtaud-Dev** [comment]
![image](https://user-images.githubusercontent.com/64975829/145067523-79a89b97-50f6-4e59-b7d7-cff0ba497b3b.png)

**Comment by AlexArtaud-Dev** [comment]
In the model, as you might see, the variable log is an object of mutliple other types (here a boolean and a string)

**Comment by AlexArtaud-Dev** [comment]
So to change any parameters that is an object, you need recursive change to handle notation like "log.channel".
Since i'm a great developper, i already created it;
So if you do "!settings log.channel <id>" it will work
The command auto handle recursive path to variable inside mongodb

**Comment by AlexArtaud-Dev** [comment]
And if you've got any problem, just contact me on discord : |Alex|#3227
I'll help you way faster than i do on github

**Comment by StrangerGithuber** [comment]
Thank you :)
