### ISSUE TITLE
Music module and update is wrong

### ISSUE THREAD

**Issue by StrangerGithuber** [AlexArtaud-Dev/Roomba-V2#4]
Hello
I am here again. 😅 I found two bugs.

One of them is:
- When I am not enabling the music then I can't use any of the commands.
- I tried to use the !setting command or other commands but it says that "The command !setting was blocked because of the music module is not activated on this server."
- If I am using for example the ping command with normal user without any roles then the same thing I get error: "The command !ping was blocked because of the music module is not activated on this server."

Second one is:
- When I am using for example !setting log.enabled true command then the update is going only to the first server.
- For example I have 5 test servers. I use the above command and the log is enabled in the first record and not in the specific record. With other words, if I am using the !setting log.enabled true command on the 4th server then the update happens in the first server record and NOT in the 4th record.

About the music bug, if I am the bot owner then I don't get that error, however if I am not the bot owner but the server owner then I get the above message.

**Comment by AlexArtaud-Dev** [comment]
Hello,

Fixed all ! Try to update your version.

**Comment by StrangerGithuber** [comment]
Yep, it works. Thanks. 👍
