### ISSUE TITLE
ParallelSaveError if many users using the bot

### ISSUE THREAD

**Issue by StrangerGithuber** [AlexArtaud-Dev/Roomba-V2#5]
Hello
I found an another bug if many servers are using the bot (in my case 5 test servers) and for example the kick command is used the same time then I get this error:

```
C:\Users\xxxx\Desktop\Roomba-V2-main\node_modules\.pnpm\mongoose@6.0.15\node_modules\mongoose\lib\model.js:481
    parallelSave = new ParallelSaveError(this);
                   ^

ParallelSaveError: Can't save() the same doc multiple times in parallel. Document: 61ae7ddcad16f8c01fa69b27
    at model.Model.save (C:\Users\xxxx\Desktop\Roomba-V2-main\node_modules\.pnpm\mongoose@6.0.15\node_modules\mongoose\lib\model.js:481:20)
    at BaseLogProvider.logCommand (C:\Users\xxxx\Desktop\Roomba-V2-main\src\logger\BaseLogProvider.js:59:49)
    at C:\Users\xxxx\Desktop\Roomba-V2-main\src\commands\moderation\kick.js:82:38
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async InteractionCollector.<anonymous> (C:\Users\xxxx\Desktop\Roomba-V2-main\src\commands\moderation\kick.js:60:13)
 ELIFECYCLE  Command failed with exit code 1.
```

It seems the log part is tricky especially BaseLogProvider.js and maybe other providers too would have problem if same time would be used.

At that line is this function:
```
async logCommand(guildID, author, command, data = null) {
        this.collection.command.push({
            guildID: guildID,
            user: {
                userID: author.id,
                userTag: author.tag,
            },
            command: {
                name: command,
                data : data
            },
            date: new Date(),
            expirationDate: new Date(new Date().getTime() + (1000 * 60 * 30))
        });
        this.collection = await this.collection.save();
    }
```

I did google little and some people said it needs to be map or foreach while saving. I found a chinese article but no idea how to implement here: https://www.coder.work/article/5083610

**Comment by AlexArtaud-Dev** [comment]
In fact it's because when you save to mongoDB a document, you can't save it from somewhere else at the same time.
I'm aware of that, and i maybe have an idea on how to fix it. I'll try to add it this weekend, since right now i'm at work.

**Comment by AlexArtaud-Dev** [comment]
One of the possibilities is to add a random timeout on the logger, to make sure even if someone spam, he can't save at the same time as someone else

**Comment by AlexArtaud-Dev** [comment]
But i have again another idea in mind to fix it way better.

**Comment by AlexArtaud-Dev** [comment]
The idea would be to add a variable to the document, if it's true, you can't save until it's false, I could call it processing, or savingStatus. So it would make sure to make a sort of "queue" to the save

**Comment by AlexArtaud-Dev** [comment]
We could also use the method `.findOneAndUpdate()` from mongoDB

**Comment by AlexArtaud-Dev** [comment]
I had some spare time, it should be fixed by now. Tell me if it's still not working !

**Comment by StrangerGithuber** [comment]
I tried your fix and it works. I will try later with more test servers but I think it fixed the problem. Thank you once again.👍
