### ISSUE TITLE
Play music

### ISSUE THREAD

**Issue by StrangerGithuber** [AlexArtaud-Dev/Roomba-V2#8]
Hello
It seems playing music doesn't work for me. I have little newer version of the package file for testing, maybe you will know what can be the problem.

My package content:

```
{
  "name": "client",
  "version": "1.0.0",
  "description": "",
  "main": "src/index.js",
  "scripts": {
    "start": "node .",
    "dev": "nodemon .",
    "test": "echo \"Error: no test specified\" && exit 1",
    "devmod": "pm2 start . --watch",
    "stop": "pm2 stop all",
    "devmonit": "pm2 monit"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@discordjs/builders": "^0.9.0",
    "@discordjs/opus": "^0.6.0",
    "@discordjs/rest": "^0.1.0-canary.0",
    "canvas": "^2.8.0",
    "colors": "^1.4.0",
    "common-tags": "^1.8.2",
    "discord-akairo": "github:discord-akairo/discord-akairo",
    "discord-api-types": "^0.25.2",
    "discord-music-player": "^8.3.1",
    "discord.js": "^13.4.0",
    "dotenv": "^10.0.0",
    "fs": "^0.0.1-security",
    "jimp": "^0.16.1",
    "moment": "^2.29.1",
    "mongoose": "^6.1.3",
    "node-fetch": "^2.6.6",
    "nodemon": "^2.0.15",
    "pm2": "^5.1.2",
    "svg-png-converter": "^0.0.9",
    "ytdl-core": "^4.9.2"
  }
}
```
I think just the discord.js is little newer compared to the repo. Maybe I overlooked something.

And I get this error when using the play command:
```
C:\Users\xxxx\Desktop\Roomba-V2-main\node_modules\.pnpm\discord-music-player@8.3.1\node_modules\discord-music-player\dist\managers\Queue.js:117
                throw new __1.DMPError(__1.DMPErrors.VOICE_CONNECTION_ERROR);
                      ^

DMPError [VoiceConnectionError]: There was an Error while starting the Voice Stream
    at Queue.<anonymous> (C:\Users\xxxx\Desktop\Roomba-V2-main\node_modules\.pnpm\discord-music-player@8.3.1\node_modules\discord-music-player\dist\managers\Queue.js:117:23)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\xxxx\Desktop\Roomba-V2-main\node_modules\.pnpm\discord-music-player@8.3.1\node_modules\discord-music-player\dist\managers\Queue.js:6:65)
```

And when I am using pnpm update command then I get this message as warning:
```
WARN  Issues with peer dependencies found
.
└─┬ discord-music-player
  └─┬ @discordjs/voice
    └─┬ prism-media
      └── ✕ unmet peer @discordjs/opus@^0.5.0: found 0.6.0
```

**Comment by AlexArtaud-Dev** [comment]
Hello, try to use discord js 13.3.1 and tell me if it fix the problem

**Comment by AlexArtaud-Dev** [comment]
Also don't forget to install FFMPEG

**Comment by AlexArtaud-Dev** [comment]
In fact i tried, the problem does not come from djs, it come from discord js opus
try to install the version 0.5.0 not the 0.6.0

**Comment by AlexArtaud-Dev** [comment]
If it does not fix the problem, try to add all the intent to the bot

**Comment by AlexArtaud-Dev** [comment]
Else, try just to clone the project again and do a npm i.
Actually all the npm packages are working for me

**Comment by StrangerGithuber** [comment]
Hmm I did all of them and same result. I downloaded the project again and setup and then using the play command but the result is same. If for you it works when you cloned again then maybe something is with my  computer ehh. I will try continue to check what can be the problem.

**Comment by StrangerGithuber** [comment]
Hmm I did all of them and same result. I downloaded the project again and setup and then using the play command but the result is same. If for you it works when you cloned again then maybe something is with my  computer ehh. I will try continue to check what can be the problem.

**Comment by AlexArtaud-Dev** [comment]
Re,
In fact it's working when i clone it again on my computer, on my dev server and on my production server.
So yes probably your computer

**Comment by StrangerGithuber** [comment]
Yeah, it seems so. Thank you for trying help me btw. I will close this because it seems this problem comes from my pc.

**Comment by StrangerGithuber** [comment]
Yeah it was my computer issue. I did reset my computer and after worked.
